name: Python Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Definimos el servicio de base de datos
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: biblioteca
        ports:
          - 3306:3306
        # El health check es vital para que las pruebas no fallen por falta de conexión inicial
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Preparar Base de Datos
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS biblioteca;"
          mysql -h 127.0.0.1 -u root -proot biblioteca < biblioteca.sql

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests
      - name: Levantar el microservicio
        run: |
          python services/usuarios/app.py &
      - name: Ejecutar pruebas con Pytest
        env:
          # Indicamos al código que la DB está en localhost para el entorno de GitHub
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: biblioteca
        run: |
          # Ejecutamos las pruebas apuntando a tu archivo de test
          pytest test/test_usuarios.py